name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Building docker image
    runs-on: ubuntu-latest #runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t flask_crud_app:${{ github.sha }} .
  
      - name: Validate docker image
        run: docker run -d --name flask_crud_app_container flask_crud_app:${{ github.sha }}

      - name: Waiting 5 sec for image run
        run: sleep 5

      - name: Validating Image by health check API
        run: curl --fail http://localhost:5000/health



